The principal components allow you to represent the data in a lower-dimensional space, capturing the most important information. This reduction in dimensionality is useful for visualization, noise reduction, and speeding up machine learning algorithms, among other applications.

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [7]:
milk = pd.read_csv("/Users/darshmac/Documents/cdac/For DBDA/Advance Analytics/Datasets/milk.csv",index_col=0)
print(milk)
scaler = StandardScaler()
m_scaled = scaler.fit_transform(milk)

            water  protein   fat  lactose   ash
Animal                                         
HORSE        90.1      2.6   1.0      6.9  0.35
ORANGUTAN    88.5      1.4   3.5      6.0  0.24
MONKEY       88.4      2.2   2.7      6.4  0.18
DONKEY       90.3      1.7   1.4      6.2  0.40
HIPPO        90.4      0.6   4.5      4.4  0.10
CAMEL        87.7      3.5   3.4      4.8  0.71
BISON        86.9      4.8   1.7      5.7  0.90
BUFFALO      82.1      5.9   7.9      4.7  0.78
GUINEA PIG   81.9      7.4   7.2      2.7  0.85
CAT          81.6     10.1   6.3      4.4  0.75
FOX          81.6      6.6   5.9      4.9  0.93
LLAMA        86.5      3.9   3.2      5.6  0.80
MULE         90.0      2.0   1.8      5.5  0.47
PIG          82.8      7.1   5.1      3.7  1.10
ZEBRA        86.2      3.0   4.8      5.3  0.70
SHEEP        82.0      5.6   6.4      4.7  0.91
DOG          76.3      9.3   9.5      3.0  1.20
ELEPHANT     70.7      3.6  17.6      5.6  0.63
RABBIT       71.3     12.3  13.1      1.

In [8]:
prcom =PCA()

In [10]:
comps = prcom.fit_transform(m_scaled)

In [11]:
print(milk.shape)
print(comps.shape)

(25, 5)
(25, 5)


In [12]:
df_comps = pd.DataFrame(comps,
                       columns=['PC1','PC2',
                               'PC3','PC4','PC5'],
                       index = milk.index)

In [14]:
print(df_comps.var())
print(prcom.explained_variance_)

PC1    4.040412
PC2    0.924372
PC3    0.134291
PC4    0.102689
PC5    0.006570
dtype: float64
[4.0404117  0.92437238 0.13429088 0.1026886  0.00656977]


In [15]:
tot_var = np.sum(prcom.explained_variance_)
prop_var = np.array(prcom.explained_variance_)/tot_var
print(prop_var)
per_var = prop_var*100
print(per_var)

[0.77575905 0.1774795  0.02578385 0.01971621 0.0012614 ]
[77.57590469 17.74794969  2.57838496  1.97162103  0.12613963]


In [17]:
print(prcom.explained_variance_)

[4.0404117  0.92437238 0.13429088 0.1026886  0.00656977]


In [ ]:
print("%age var explained by 1st ",77.57590469 +17.74794969)